version: 0.1
phases:
  install:
    commands:
      - npm install
      - echo ${BUCKET}
      - ./node_modules/typescript/bin/tsc
      - aws cloudformation package --template-file template.yaml --s3-bucket ${BUCKETNAME} --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - outputtemplate.yaml
