AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda_workshop

  Sample SAM Template for lambda_workshop
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaWorkshop:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dist/
      Handler: app.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          BUCKETNAME: lwjd01
      Events:
        Workshop:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /function
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaWorkshopApi:
    Description: "API Gateway endpoint URL for Prod stage for your function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/function/"
  LambdaWorkshop:
    Description: "Your Lambda Function ARN"
    Value: !GetAtt LambdaWorkshop.Arn
  LambdaWorkshopIamRole:
    Description: "Implicit IAM Role created for your function"
    Value: !GetAtt LambdaWorkshopRole.Arn
